# Generated by Django 4.0.5 on 2022-07-07 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateTagsDemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demo_integer', models.IntegerField(choices=[(1, 'one'), (2, 'two'), (3, 'three')], verbose_name='Demo Integer Field with Choices')),
                ('demo_char', models.CharField(max_length=100)),
            ],
        ),
    ]
